[build]
  command = "cd material-kit-react-main && npm run build"
  publish = "material-kit-react-main/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200