[build]
  command = "pnpm install --prefer-offline --no-frozen-lockfile --force && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NETLIFY_SKIP_GO_INSTALL = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200