[build]
  # Remove this line as it's causing path confusion
  # base = "material-kit-react-main"
  command = "NODE_OPTIONS='--max_old_space_size=4096' pnpm install --no-frozen-lockfile && pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200