# Generated by Django 5.1.7 on 2025-03-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harsh_braking_weight', models.IntegerField(default=20)),
                ('harsh_acceleration_weight', models.IntegerField(default=10)),
                ('swerving_weight', models.IntegerField(default=30)),
                ('over_speed_weight', models.IntegerField(default=20)),
                ('potential_swerving_weight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scorepattern',
            constraint=models.CheckConstraint(
                check=models.Q(('customer_id__isnull', False)) | models.Q(('company_id__isnull', False)),
                name='score_pattern_customer_or_company'
            ),
        ),
    ]