# Generated by Django 5.1.7 on 2025-03-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='api.car'),
        ),
    ]
