# Generated by Django 5.1.5 on 2025-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingdata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
