# Generated by Django 5.1.5 on 2025-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drivingdata_latitude_drivingdata_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivingdata',
            old_name='acceleration',
            new_name='ax',
        ),
        migrations.RenameField(
            model_name='drivingdata',
            old_name='bumps',
            new_name='ay',
        ),
        migrations.RenameField(
            model_name='drivingdata',
            old_name='drilling',
            new_name='az',
        ),
        migrations.RenameField(
            model_name='drivingdata',
            old_name='accident_detection',
            new_name='counter',
        ),
        migrations.RenameField(
            model_name='drivingdata',
            old_name='harsh_braking',
            new_name='gx',
        ),
        migrations.RenameField(
            model_name='drivingdata',
            old_name='swerving',
            new_name='gy',
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='gz',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='pitch',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='roll',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='yaw',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
