# Generated by Django 5.1.5 on 2025-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_acceleration_drivingdata_ax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driving_data',
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='gz',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='roll',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='drivingdata',
            name='yaw',
            field=models.FloatField(default=0.0),
        ),
    ]
